name: Update module
on:
  repository_dispatch:
    types: update
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.DOC_REPO_SECRET }}
          submodules: recursive
      - name: Update module
        run: |
          #git config pull.rebase false
          git config --global user.name "GitHub Action"
          git config --global user.email "noreply@github.com"
          #git submodule foreach git pull origin weblate-translations --rebase --allow-unrelated-histories
          git submodule foreach git pull origin weblate-translations --no-rebase --allow-unrelated-histories
          git submodule foreach git merge origin origin/weblate-translations --allow-unrelated-histories
          git commit -am "deploy: ${{github.event.client_payload.module}} - ${{github.event.client_payload.sha}}"
          git push

          
